---
- name: Insert Configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 660
    owner: root
    group: root

- name: Restart SSH service
  ansible.builtin.service:
    name: ssh
    state: restarted
